import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full bg-[#f0f0f0] text-[16px] flex justify-center items-center">
        <div className="flex max-w-[1585px] pt-2 bg-white flex-col justify-center items-center">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
